### ISSUE TITLE
función trim() devuelve cero.

### ISSUE THREAD

**Issue by aradillo** [jlongi/Editor-DescartesJS#1]
Pasos a reproducir:
1. Agregar gráfico tipo texto.
2. En el parámetro _texto_ del mismo, incluir [trim('   Hola   ')] y pulsar _Aplicar_.

Resultados esperados:
1. Se agrega el gráfico.
2. Tras aplicar, aparece _Hola_ sin espacios. Sin embargo, devuelve el valor cero (0.00).
[trim_cero.zip](https://github.com/jlongi/Editor-DescartesJS/files/3499069/trim_cero.zip)

**Comment by jlongi** [comment]
El problema se encontraba en que el código de la función trim, no se encontraba en el intérprete. 
Ya se agregó el código correspondiente [commit 8a4ac2118b8335166516bb83734e42c49377608e](https://github.com/jlongi/DescartesJS/commit/8a4ac2118b8335166516bb83734e42c49377608e) en el repositorio del intérprete.
