### ISSUE TITLE
No puedo instalar en linux

### ISSUE THREAD

**Issue by LuisOropeza7** [jlongi/Editor-DescartesJS#7]
No sé como contactar y en la documentación no encontré nada acerca de la instalación en linux.

ejecuto el archivo .run y me genera accesos directos pero no ejecutan el programa. Tambien fue a la runta /opt/DescartesJS que segun la info de los archivos .desktop son la ruta en la que se ejecuta el .bin pero el archivo .bin tampoco ejecuta el programa. No sé si hay dependencias necesarias a instalar. 

uso fedora 34 como distribución de linux. ayuda no sé donde contactar :(

**Comment by jlongi** [comment]
Hola, he tenido problemas con la creación de un instalador propio para linux. En este momento actualice y sustituí los archivos de instalación para linux:
https://github.com/jlongi/Editor-DescartesJS/releases/download/Instaladores/EditorDescartesJS_Linux_ia32.tar.gz
https://github.com/jlongi/Editor-DescartesJS/releases/download/Instaladores/EditorDescartesJS_Linux_x64.tar.gz
solo es necesario descargar el archivo dependiendo de si utilizas un sistema de 32 o 64bits y extraerlo en el lugar donde quieras ponerlo, y desde una terminal ejecutar el archivo DescartesJS, en caso de que no se ejecute puede ser que haya perdido el permiso de ejecución, por lo que basta realizar desde una terminal: chmod +x DescartesJS
Espero te sea de utilidad.

**Comment by LuisOropeza7** [comment]
Muchas gracias! ahora si funciono.
